version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: strategybuilder-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blockbuilders
      POSTGRES_USER: blockbuilders
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockbuilders"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  redis:
    image: redis:7-alpine
    container_name: strategybuilder-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
